# Generated by Django 5.2.7 on 2025-10-13 10:19

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import saleor.core.utils.json_serializer
import saleor.webhook.models
import saleor.webhook.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('target_url', saleor.webhook.models.WebhookURLField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_query', models.TextField(blank=True, null=True)),
                ('custom_headers', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True, validators=[saleor.webhook.validators.custom_headers_validator])),
                ('filterable_channel_slugs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=500)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='app.app')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=128, verbose_name='Event type')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='webhook.webhook')),
            ],
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=django.contrib.postgres.indexes.GinIndex(fields=['filterable_channel_slugs'], name='filterable_channel_slugs_idx'),
        ),
    ]
