# Generated by Django 5.2.7 on 2025-10-13 10:19

import saleor.core.utils.json_serializer
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('local', 'local'), ('thirdparty', 'thirdparty')], default='local', max_length=60)),
                ('identifier', models.CharField(blank=True, max_length=256)),
                ('about_app', models.TextField(blank=True, null=True)),
                ('data_privacy', models.TextField(blank=True, null=True)),
                ('data_privacy_url', models.URLField(blank=True, null=True)),
                ('homepage_url', models.URLField(blank=True, null=True)),
                ('support_url', models.URLField(blank=True, null=True)),
                ('configuration_url', models.URLField(blank=True, null=True)),
                ('app_url', models.URLField(blank=True, null=True)),
                ('manifest_url', models.URLField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=60, null=True)),
                ('audience', models.CharField(blank=True, max_length=256, null=True)),
                ('is_installed', models.BooleanField(default=True)),
                ('author', models.CharField(blank=True, max_length=60, null=True)),
                ('brand_logo_default', models.ImageField(blank=True, null=True, upload_to='app-brand-data')),
            ],
            options={
                'ordering': ('name', 'pk'),
                'permissions': (('manage_apps', 'Manage apps'), ('manage_observability', 'Manage observability')),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('url', models.URLField()),
                ('mount', models.CharField(choices=[('category_overview_create', 'category_overview_create'), ('category_overview_more_actions', 'category_overview_more_actions'), ('category_details_more_actions', 'category_details_more_actions'), ('collection_overview_create', 'collection_overview_create'), ('collection_overview_more_actions', 'collection_overview_more_actions'), ('collection_details_more_actions', 'collection_details_more_actions'), ('collection_details_widgets', 'collection_details_widgets'), ('gift_card_overview_create', 'gift_card_overview_create'), ('gift_card_overview_more_actions', 'gift_card_overview_more_actions'), ('gift_card_details_more_actions', 'gift_card_details_more_actions'), ('gift_card_details_widgets', 'gift_card_details_widgets'), ('customer_overview_create', 'customer_overview_create'), ('customer_overview_more_actions', 'customer_overview_more_actions'), ('customer_details_more_actions', 'customer_details_more_actions'), ('customer_details_widgets', 'customer_details_widgets'), ('product_overview_create', 'product_overview_create'), ('product_overview_more_actions', 'product_overview_more_actions'), ('product_details_more_actions', 'product_details_more_actions'), ('product_details_widgets', 'product_details_widgets'), ('navigation_catalog', 'navigation_catalog'), ('navigation_orders', 'navigation_orders'), ('navigation_customers', 'navigation_customers'), ('navigation_discounts', 'navigation_discounts'), ('navigation_translations', 'navigation_translations'), ('navigation_pages', 'navigation_pages'), ('order_details_more_actions', 'order_details_more_actions'), ('order_overview_create', 'order_overview_create'), ('order_overview_more_actions', 'order_overview_more_actions'), ('order_details_widgets', 'order_details_widgets'), ('draft_order_details_more_actions', 'draft_order_details_more_actions'), ('draft_order_overview_create', 'draft_order_overview_create'), ('draft_order_overview_more_actions', 'draft_order_overview_more_actions'), ('draft_order_details_widgets', 'draft_order_details_widgets'), ('discount_details_more_actions', 'discount_details_more_actions'), ('discount_overview_create', 'discount_overview_create'), ('discount_overview_more_actions', 'discount_overview_more_actions'), ('voucher_details_more_actions', 'voucher_details_more_actions'), ('voucher_overview_create', 'voucher_overview_create'), ('voucher_overview_more_actions', 'voucher_overview_more_actions'), ('voucher_details_widgets', 'voucher_details_widgets'), ('page_details_more_actions', 'page_details_more_actions'), ('page_overview_create', 'page_overview_create'), ('page_overview_more_actions', 'page_overview_more_actions'), ('page_type_overview_create', 'page_type_overview_create'), ('page_type_overview_more_actions', 'page_type_overview_more_actions'), ('page_type_details_more_actions', 'page_type_details_more_actions'), ('menu_overview_create', 'menu_overview_create'), ('menu_overview_more_actions', 'menu_overview_more_actions'), ('menu_details_more_actions', 'menu_details_more_actions')], max_length=256)),
                ('target', models.CharField(choices=[('popup', 'popup'), ('app_page', 'app_page'), ('new_tab', 'new_tab'), ('widget', 'widget')], default='popup', max_length=128)),
                ('http_target_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='pending', max_length=50)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('app_name', models.CharField(max_length=60)),
                ('manifest_url', models.URLField()),
                ('brand_logo_default', models.ImageField(blank=True, null=True, upload_to='app-installation-brand-data')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('auth_token', models.CharField(max_length=128, unique=True)),
                ('token_last_4', models.CharField(max_length=4)),
            ],
        ),
    ]
