# Generated by Django 5.2.7 on 2025-10-13 10:19

import datetime
import django.contrib.postgres.indexes
import django_countries.fields
import saleor.core.utils.json_serializer
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('name', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('currency_code', models.CharField(max_length=3)),
                ('default_country', django_countries.fields.CountryField(max_length=2)),
                ('allocation_strategy', models.CharField(choices=[('prioritize-sorting-order', 'Prioritize sorting order'), ('prioritize-high-stock', 'Prioritize high stock')], default='prioritize-sorting-order', max_length=255)),
                ('order_mark_as_paid_strategy', models.CharField(choices=[('transaction_flow', 'Use transaction'), ('payment_flow', 'Use payment')], default='payment_flow', max_length=255)),
                ('default_transaction_flow_strategy', models.CharField(choices=[('authorization', 'Authorize'), ('charge', 'Charge')], default='charge', max_length=255)),
                ('automatically_confirm_all_new_orders', models.BooleanField(default=True, null=True)),
                ('allow_unpaid_orders', models.BooleanField(default=False)),
                ('automatically_fulfill_non_shippable_gift_card', models.BooleanField(default=True, null=True)),
                ('expire_orders_after', models.IntegerField(blank=True, default=None, null=True)),
                ('delete_expired_orders_after', models.DurationField(default=datetime.timedelta(days=60))),
                ('include_draft_order_in_voucher_usage', models.BooleanField(default=False)),
                ('use_legacy_error_flow_for_checkout', models.BooleanField(default=True)),
                ('automatically_complete_fully_paid_checkouts', models.BooleanField(default=False)),
                ('draft_order_line_price_freeze_period', models.PositiveIntegerField(blank=True, default=24, null=True)),
                ('use_legacy_line_discount_propagation_for_order', models.BooleanField(default=True)),
                ('release_funds_for_expired_checkouts', models.BooleanField(default=False)),
                ('checkout_ttl_before_releasing_funds', models.DurationField(default=datetime.timedelta(seconds=21600))),
                ('checkout_release_funds_cut_off_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('slug',),
                'permissions': (('manage_channels', 'Manage channels.'),),
                'abstract': False,
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='channel_p_meta_idx'), django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='channel_meta_idx')],
            },
        ),
    ]
