# Generated by Django 5.2.7 on 2025-10-29 13:51

import django.db.models.deletion
import user_profile.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', user_profile.models.PossiblePhoneNumberField(blank=True, db_index=True, default='', max_length=128, null=True, region=None)),
                ('channels', models.ManyToManyField(blank=True, help_text='Channels this user has access to.', related_name='user_profiles', to='channel.channel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
