# Generated by Django 5.2.7 on 2025-10-13 10:19

import django.contrib.postgres.indexes
import saleor.core.utils.json_serializer
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(db_index=True, editable=False, null=True)),
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(blank=True, max_length=256, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuItemTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=35)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ('language_code', 'menu_item', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('manage_menus', 'Manage navigation.'),),
                'abstract': False,
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='menu_p_meta_idx'), django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='menu_meta_idx')],
            },
        ),
    ]
