# Generated by Django 5.2.7 on 2025-10-27 08:16

import saleor.account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=saleor.account.models.PossiblePhoneNumberField(blank=True, db_index=True, default='', max_length=128, null=True, region=None),
        ),
    ]
