# Generated by Django 5.2.7 on 2025-10-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_mobile'),
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channels',
            field=models.ManyToManyField(blank=True, help_text='Channels this user has access to.', related_name='users', to='channel.channel'),
        ),
    ]
