# Generated by Django 5.2.7 on 2025-10-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_channels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='channels',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
    ]
