# Generated by Django 5.2.7 on 2025-10-30 21:51

import saleor.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_channels_remove_user_mobile'),
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channels',
            field=models.ManyToManyField(blank=True, help_text='Channels this user has access to.', related_name='users', to='channel.channel'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=saleor.account.models.PossiblePhoneNumberField(blank=True, db_index=True, default='', max_length=128, null=True, region=None),
        ),
    ]
