# Generated by Django 5.2.7 on 2025-11-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_channels_user_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='channels',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
    ]
