# Generated by Django 5.2.7 on 2025-10-13 10:19

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import saleor.core.db.fields
import saleor.core.utils.editorjs
import saleor.core.utils.json_serializer
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
            ],
            options={
                'ordering': ('slug',),
                'permissions': (('manage_page_types_and_attributes', 'Manage page types and attributes.'),),
                'abstract': False,
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='pagetype_p_meta_idx'), django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='pagetype_meta_idx'), django.contrib.postgres.indexes.GinIndex(fields=['name', 'slug'], name='page_pagety_name_7c1cb8_gin')],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('seo_title', models.CharField(blank=True, max_length=70, null=True, validators=[django.core.validators.MaxLengthValidator(70)])),
                ('seo_description', models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('content', saleor.core.db.fields.SanitizedJSONField(blank=True, null=True, sanitizer=saleor.core.utils.editorjs.clean_editor_js)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('search_index_dirty', models.BooleanField(db_default=True, default=True)),
                ('page_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='page.pagetype')),
            ],
            options={
                'ordering': ('slug',),
                'permissions': (('manage_pages', 'Manage pages.'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=35)),
                ('seo_title', models.CharField(blank=True, max_length=70, null=True, validators=[django.core.validators.MaxLengthValidator(70)])),
                ('seo_description', models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', saleor.core.db.fields.SanitizedJSONField(blank=True, null=True, sanitizer=saleor.core.utils.editorjs.clean_editor_js)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='page.page')),
            ],
            options={
                'ordering': ('language_code', 'page', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'slug'), name='uniq_lang_slug_pagetransl')],
                'unique_together': {('language_code', 'page')},
            },
        ),
        migrations.AddIndex(
            model_name='page',
            index=django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='page_p_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='page_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='page_tsearch'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['slug'], name='page_slug_btree_idx'),
        ),
    ]
